### ISSUE TITLE
nphoton variable using photon IDMVA WP80

### ISSUE THREAD

**Issue by andersbarzdukas** [richstu/nano2pico#12]
1. Want to change the nphoton variable to use the photon idmva wp80 selection instead of the HIG-019-014 working point.
2. Change the minimum deltaR(gamma,l) requirement to > 0.3 from >0.4.
3. Use the photon_elidx variable to reject photons that point to signal electrons.

(Edited to adapt comment below from Michael)

**Comment by mcoshiro** [comment]
Hijacking this: suggested changes to definition of signal photon (photon_sig and thus nphoton) including loosening drmin requirement to 0.3 and requiring photon_elidx does not point to a signal electron. On the note of WP80, we can use the central one for now, but we may want to re-optimize once we have derived photon corrections

**Comment by andersbarzdukas** [comment]
Hey Michael, I was going to submit these as different issues, but we can combine them into one!

**Comment by andersbarzdukas** [comment]
Have added these changes. For the deltaR > 0.3 and photon_idmva change I have added plots on skims ((N_e >=2 || N_mu >=2) && Nphoton >= 1) where there are no additional selections (plot says nphoton>0 which is included in the skim selection). These plots use the 2016 picos produced in the htozgamma_kingscanyon_v1.addingkinematicfit/ folder.
[TestPico_KF_ggF_deltaR_gammal__photon_drmin0__wgt_1invfb__lumi_nonorm_lin.pdf](https://github.com/richstu/nano2pico/files/14607422/TestPico_KF_ggF_deltaR_gammal__photon_drmin0__wgt_1invfb__lumi_nonorm_lin.pdf)
[TestPico_KF_ggF_idmva_ngamma_g0__photon_idmva0__wgt_1invfb__lumi_nonorm_lin.pdf](https://github.com/richstu/nano2pico/files/14607423/TestPico_KF_ggF_idmva_ngamma_g0__photon_idmva0__wgt_1invfb__lumi_nonorm_lin.pdf)
