### ISSUE TITLE
Add additional commonly used variables to pico

### ISSUE THREAD

**Issue by mcoshiro** [richstu/nano2pico#21]
Namely, a branch for the year-dependent pT cuts was suggested by Jaebak.

**Comment by jaebak** [comment]
I also wonder how about the below variables

- max_dR
- l1_pt
- l2_pt
- l1_phi
- l2_phi
- l1_eta
- l2_eta

**Comment by mcoshiro** [comment]
I'm not sure which max dR you are referring to, but if it is between a photon and lepton, than all of these variables are already in pico, with the names photon_drmax, lep_pt[0], lep_pt[1], lep_phi[0], lep_phi[1], lep_eta[0], and lep_eta[1]. The lep_ variables are removed in slims, however, so we could add them back

**Comment by jaebak** [comment]
Hi Michael, you are right. Thanks for the correction.

**Comment by andersbarzdukas** [comment]
I  made the listed changes in the pull request I made so I will link this. There is a max and min DR(gamma,jet) for the two jets. Do we want the min and max variables or split it by leading an subleading jets?

Also are there other variables we want to include?
