### ISSUE TITLE
Review for nanoAODv12: type changes and branch names

### ISSUE THREAD

**Issue by jdgrassi** [richstu/nano2pico#30]
Review any possible changes in branch names with the shift to nanoAODv12, as well as type changes occurring between v11 and v12. Pass photon mva variables that are present to picos
Other changes. . .

**Comment by rzouCERN** [comment]
Here's my notes on what changed between v11 and v12.

nCorrT1METJet	UInt_t  → nCorrT1METJet	Int_t
Electron_genPartIdx	Int_t(index to Genpart) → Short_t(index to Genpart)
Electron_jetIdx	Int_t(index to Jet) → Short_t(index to Jet)
Electron_photonIdx	Int_t(index to Photon) → Short_t(index to Photon)
Electron_tightCharge	Int_t → UChar_t
nElectron	UInt_t →  Int_t
FsrPhoton_muonIdx	Int_t(index to Muon) → Short_t(index to Muon)
nFsrPhoton	UInt_t → Int_t
GenPart_genPartIdxMother	Int_t(index to Genpart) → Short_t(index to Genpart)
GenPart_statusFlags	Int_t → UShort_t 
nGenPart	UInt_t → Int_t
nLHEPart	UInt_t	 → Int_t
nLHEPdfWeight	UInt_t	→ Int_t
nLHEReweightingWeight	UInt_t	→ Int_t
nLHEScaleWeight	UInt_t → Int_t
Muon_fsrPhotonIdx	Int_t(index to Fsrphoton) → Short_t(index to Fsrphoton)
Muon_genPartIdx	Int_t → Short_t(index to Genpart) 
Muon_jetIdx	Int_t → Short_t
Muon_nStations	Int_t → UChar_t
Muon_nTrackerLayers	Int_t → UChar_t
Muon_tightCharge	Int_t → UChar_t
nMuon	UInt_t → Int_t
nOtherPV	UInt_t → Int_t
nPSWeight  UInt_t → Int_t
PV_npvs	Int_t → UChar_t
PV_npvsGood	Int_t → UChar_t
Photon_cutBased	Int_t → UChar_t
Photon_electronIdx	Int_t → Short_t
Photon_genPartIdx	Int_t → Short_t
Photon_jetIdx	Int_t → Short_t
nPhoton	UInt_t → Int_t
SV_charge	Short_t → Int_t
nSV	Int_t → UInt_t
nSoftActivityJet	Int_t → UInt_t
nSubGenJetAK8	Int_t → UInt_t

Things removed:
Electron_cleanmask
Electron_dEscaleDown
Electron_dEscaleUp
Electron_dEsigmaDown
Electron_dEsigmaUp
Electron_mvaFall17V2Iso	Float_t	MVA Iso ID V2 score
Electron_mvaFall17V2Iso_WP80	Bool_t	MVA Iso ID V2 WP80
Electron_mvaFall17V2Iso_WP90	Bool_t	MVA Iso ID V2 WP90
Electron_mvaFall17V2Iso_WPL	Bool_t	MVA Iso ID V2 loose WP
Electron_mvaFall17V2noIso	Float_t	MVA noIso ID V2 score
Electron_mvaFall17V2noIso_WP80	Bool_t	MVA noIso ID V2 WP80
Electron_mvaFall17V2noIso_WP90	Bool_t	MVA noIso ID V2 WP90
Electron_mvaFall17V2noIso_WPL	Bool_t	MVA noIso ID V2 loose WP
Muon_mvaId	UChar_t	Mva ID from miniAOD selector (1=MvaLoose, 2=MvaMedium, 3=MvaTight, 4=MvaVTight, 5=MvaVVTight)
Muon_mvaLowPt	Float_t	Low pt muon ID score
Muon_mvaLowPtId	UChar_t	Low Pt Mva ID from miniAOD selector (1=LowPtMvaLoose, 2=LowPtMvaMedium)
Muon_cleanmask
Photon_charge
Photon_cleanmask
Photon_cutBased_Fall17V1Bitmap
Photon_dEscaleDown	Float_t
Photon_dEscaleUp	Float_t
Photon_dEsigmaDown	Float_t
Photon_dEsigmaUp	Float_t
Photon_eCorr	Float_t
Photon_mass	Float_t
Photon_mvaID_Fall17V2	Float_t	MVA ID score, Fall17V2
Photon_mvaID_Fall17V2_WP80	Bool_t	MVA ID WP80, Fall17V2
Photon_mvaID_Fall17V2_WP90	Bool_t	MVA ID WP90, Fall17V2
Photon_pfRelIso03_all_Fall17V2
Photon_pfRelIso03_chg_Fall17V2
Photon_vidNestedWPBitmap_Fall17V2
Rho_*

Things added: 
Electron_fsrPhotonIdx	Short_t(index to Fsrphoton)	Index of the lowest-dR/ET2 among associated FSR photons
Electron_seediEtaOriX	Char_t	iEta or iX of seed crystal. iEta is barrel-only, iX is endcap-only. iEta runs from -85 to +85, with no crystal at iEta=0. iX runs from 1 to 100.
Electron_seediPhiOriY	Int_t	iPhi or iY of seed crystal. iPhi is barrel-only, iY is endcap-only. iPhi runs from 1 to 360. iY runs from 1 to 100.
Electron_svIdx	Short_t(index to Sv)	index of matching secondary vertex
Electron_mvaHZZIso	Float_t	HZZ MVA Iso ID score
Electron_mvaIso	Float_t	MVA Iso ID score, Winter22V1
Electron_mvaIso_WP80	Bool_t	MVA Iso ID WP80, Winter22V1
Electron_mvaIso_WP90	Bool_t	MVA Iso ID WP90, Winter22V1
Electron_mvaNoIso	Float_t	MVA noIso ID score, Winter22V1
Electron_mvaNoIso_WP80	Bool_t	MVA noIso ID WP80, Winter22V1
Electron_mvaNoIso_WP90	Bool_t	MVA noIso ID WP90, Winter22V1

FsrPhoton_electronIdx	Short_t(index to Electron)

Muon_mvaLowPt	Float_t	Low pt muon ID score
Muon_mvaMuID	Float_t	MVA-based ID score
Muon_mvaMuID_WP	UChar_t	MVA-based ID selector WPs (1=MVAIDwpMedium,2=MVAIDwpTight)
Muon_bsConstrainedChi2	Float_t	chi2 of beamspot constraint
Muon_bsConstrainedPt	Float_t	pT with beamspot constraint
Muon_bsConstrainedPtErr	Float_t	pT error with beamspot constraint
Muon_svIdx	Short_t(index to Sv)   index of matching secondary vertex
OtherPV_z	Float_t	Z position of other primary vertices, excluding the main PV
Photon_ecalPFClusterIso	Float_t	sum pt of ecal clusters, vetoing clusters part of photon
Photon_energyRaw	Float_t	raw energy of photon supercluster
Photon_esEffSigmaRR	Float_t	preshower sigmaRR
Photon_esEnergyOverRawE	Float_t	ratio of preshower energy to raw supercluster energy
Photon_etaWidth	Float_t	Width of the photon supercluster in eta
Photon_haloTaggerMVAVal	Float_t	Value of MVA based BDT based beam halo tagger in the Ecal endcap (valid for pT > 200 GeV)
Photon_hasConversionTracks	Bool_t	Variable specifying if photon has associated conversion tracks (one-legged or two-legged)
Photon_hcalPFClusterIso	Float_t	sum pt of hcal clusters, vetoing clusters part of photon
Photon_hoe_PUcorr	Float_t	PU corrected H/E (cone-based with quadraticEA x rho x rho + linearEA x rho Winter22V1 corrections)
Photon_pfChargedIso	Float_t	PF absolute isolation dR=0.3, charged component with dxy,dz match to PV
Photon_trkSumPtHollowConeDR03	Float_t	Sum of track pT in a hollow cone of outer radius, inner radius
Photon_trkSumPtSolidConeDR04	Float_t	Sum of track pT in a cone of dR=0.4

**Comment by rzouCERN** [comment]
most significant change:
Added electron_fsrphotonidx and FsrPhoton_electronIdx in pico. 
v12 no longer has DeepB. I changed to using PNetB as default for 2022 and 2023/nanoaodv12. Implemented btag_wps for PNetB for 2022, 2022EE, 2023, 2023BPix. 
Also switched to using HZZ electron mva as default. See issue #44 .
