### ISSUE TITLE
Switch to HZZ ID for run 3 electrons

### ISSUE THREAD

**Issue by mcoshiro** [richstu/nano2pico#44]
Score is stored in branch `Electron_mvaHZZIso`, just need to look up WP to add cut

**Comment by rzouCERN** [comment]
Implemented the 2018UL WPs for 2022,2023 according to twiki: https://twiki.cern.ch/twiki/bin/viewauth/CMS/MultivariateElectronIdentificationRun2#HZZ_MVA_training_details_and_wor.

See reference talk (where they mentioned they are using 2018UL WP for early Run3): https://indico.cern.ch/event/1360899/contributions/5780705/attachments/2788255/4861818/ElectronIDandSFs_HZZ.pdf

Note for a small difference: looking at their source code, they use supercluster eta for the categories. I'm using the electron eta.
