### ISSUE TITLE
event_weighter.bTaggingSF crashing for data

### ISSUE THREAD

**Issue by jaebak** [richstu/nano2pico#5]
https://github.com/richstu/nano2pico/blob/0158da852e7370577caf84116c34e8b6d70a44b3/src/event_weighter.cpp#L159

will crash for data, because out_jet_hflavor does not exist for data.
The SF should be handled differently for data.

**Comment by psiddire** [comment]
Scale factors are only required for MC, so moved "event_weighter.bTaggingSF" to "!isData" condition.

**Comment by jaebak** [comment]
https://github.com/richstu/nano2pico/blob/55d22c5fa1a14399b3760c579b16916a760e5575/src/process_nano.cxx#L346-L354

Wouldn't b-tag scale factors be used for zgamma for the ttH category for example?

**Comment by psiddire** [comment]
Changed implementation to this: https://github.com/richstu/nano2pico/blob/master/src/process_nano.cxx#L346-L352
